/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: ffde0fdd98c62ef062f8a498dd56801d)
interface __BaseEnv_Env {
	DORA_CACHE: KVNamespace;
	ATLAS_NOTIFY: Fetcher /* atlas-notify */;
	ATLAS_BLACKBOX: Fetcher /* atlas-blackbox */;
	DEPLOY_WATCH: Fetcher /* deploy-watch */;
	ATLAS_API_PUBLIC: Fetcher /* atlas-api-public */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/public-boundary");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
