/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: ea461be18c5004dbebc092c33ca58f03)
interface __BaseEnv_Env {
	DORA_CACHE: KVNamespace;
	ATLAS_NOTIFY: Fetcher /* atlas-notify */;
	ATLAS_BLACKBOX: Fetcher /* atlas-blackbox */;
	DEPLOY_WATCH: Fetcher /* deploy-watch */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
