/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b69321af515d7f52b6e96a3e4d911f76)
interface __BaseEnv_Env {
	DORA_CACHE: KVNamespace;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
